{
  "include": [],
  "exclude": [
    "**/*.[bB][aA][kK]",
    "**/*.[cC][jJ][sS]",
    "**/*.[dD][oO][cC][xX]",
    "**/*.[jJ][sS][oO][nN]",
    "**/*.[lL][oO][gG]",
    "**/*.[mM][dD]",
    "**/*.[pP][sS]1",
    "**/*.[pP][yY]",
    "**/*.[pP][yY][cC]",
    "**/*.[tT][mM][pP]",
    "**/*.[yY][aA][mM][lL]",
    "**/*.[yY][mM][lL]",
    "**/*.[zZ][iI][pP]",
    "**/*.bak",
    "**/*.cjs",
    "**/*.docx",
    "**/*.json",
    "**/*.log",
    "**/*.md",
    "**/*.ps1",
    "**/*.py",
    "**/*.pyc",
    "**/*.tmp",
    "**/*.yaml",
    "**/*.yml",
    "**/*.zip",
    "**/AGENTS.md",
    "**/README.md",
    "**/[aA][gG][eE][nN][tT][sS].[mM][dD]",
    "**/[eE][xX][eE][mM][pP][lL][oO][sS]",
    "**/[fF][iI][xX][tT][uU][rR][eE][sS]",
    "**/[mM][aA][nN][iI][fF][eE][sS][tT][sS]",
    "**/[nN][oO][dD][eE]_[mM][oO][dD][uU][lL][eE][sS]",
    "**/[rR][eE][aA][dD][mM][eE].[mM][dD]",
    "**/[rR][eE][lL][aA][tT][oO][rR][iI][oO][sS]",
    "**/[rR][eE][pP][oO][rR][tT][sS]",
    "**/[tT][eE][mM][pP]",
    "**/[tT][eE][sS][tT]",
    "**/[tT][eE][sS][tT][sS]",
    "**/[tT][mM][pP]",
    "**/[vV][eE][nN][dD][oO][rR]",
    "**/exemplos",
    "**/fixtures",
    "**/manifests",
    "**/node_modules",
    "**/relatorios",
    "**/reports",
    "**/temp",
    "**/test",
    "**/tests",
    "**/tmp",
    "**/vendor",
    "*.[bB][aA][kK]",
    "*.[cC][jJ][sS]",
    "*.[dD][oO][cC][xX]",
    "*.[jJ][sS][oO][nN]",
    "*.[lL][oO][gG]",
    "*.[mM][dD]",
    "*.[pP][sS]1",
    "*.[pP][yY]",
    "*.[pP][yY][cC]",
    "*.[tT][mM][pP]",
    "*.[yY][aA][mM][lL]",
    "*.[yY][mM][lL]",
    "*.[zZ][iI][pP]",
    "*.bak",
    "*.cjs",
    "*.docx",
    "*.json",
    "*.log",
    "*.md",
    "*.ps1",
    "*.py",
    "*.pyc",
    "*.tmp",
    "*.yaml",
    "*.yml",
    "*.zip",
    "AGENTS.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "[aA][gG][eE][nN][tT][sS].[mM][dD]",
    "[eE][xX][eE][mM][pP][lL][oO][sS]",
    "[fF][iI][xX][tT][uU][rR][eE][sS]",
    "[gG][eE][mM][fF][iI][lL][eE]",
    "[gG][eE][mM][fF][iI][lL][eE].[lL][oO][cC][kK]",
    "[mM][aA][nN][iI][fF][eE][sS][tT][sS]",
    "[nN][oO][dD][eE]_[mM][oO][dD][uU][lL][eE][sS]",
    "[rR][eE][aA][dD][mM][eE].[mM][dD]",
    "[rR][eE][lL][aA][tT][oO][rR][iI][oO][sS]",
    "[rR][eE][pP][oO][rR][tT][sS]",
    "[tT][eE][mM][pP]",
    "[tT][eE][sS][tT]",
    "[tT][eE][sS][tT][sS]",
    "[tT][mM][pP]",
    "[vV][eE][nN][dD][oO][rR]",
    "_[pP][rR][oO][dD][uU][cC][aA][oO]",
    "_producao",
    "exemplos",
    "fixtures",
    "manifests",
    "node_modules",
    "relatorios",
    "reports",
    "temp",
    "test",
    "tests",
    "tmp",
    "vendor"
  ]
}
